### ISSUE TITLE
`true`/`false` need special handling in `bool` declaration

### ISSUE THREAD

**Issue by metagn** [nim-lang/nimony#223]
```nim
type bool {.magic: Bool.} = enum
  false = 0, true = 1
let x: bool = true # Error: expected `bool` but got: bool.0.abcdefgh
```

1. Their type needs to be inlined into the magic `(bool)`
2. They themselves need to be inlined into `(true)`/`(false)`

Since `bool` is the only magic enum, we should be able to special case it

**Comment by Araq** [comment]
On the other hand, we could also do:

```nim

type bool {.magic: Bool.}
const
  false {.magic: False.} = bool(0)
  true {.magic: True.} = bool(1)

```

We need magic consts for `isMainModule` anyway.
